const SETLOADING = 'SETLOADING';
const SETCOLLECTIONS = 'SETCOLLECTIONS';
const SETFETCHERROR = 'SETFETCHERROR';
const SETGAME = 'SETGAMES';

export {
    SETLOADING,
    SETCOLLECTIONS,
    SETGAME,
    SETFETCHERROR
}