const SETLOADING = 'SETLOADING';
const SETCOLLECTIONS = 'SETCOLLECTIONS';
const SETCOLLECTION = 'SETCOLLECTION';
const SETGAMES = 'SETGAMES';
const SETFETCHERROR = 'SETFETCHERROR';
const SETGAME = 'SETSELECTEDGAME';
const SETCARTDATA = 'SETCARTDATA';
const OPENSIDEBAR = 'OPENSIDEBAR';

export {
    SETLOADING,
    SETCOLLECTIONS,
    SETGAME,
    SETFETCHERROR,
    SETCARTDATA,
    OPENSIDEBAR,
    SETCOLLECTION,
    SETGAMES
}